# Claude Code 项目配置文件
# 企业管理系统项目专用配置

# 自动执行设置
auto_approve: true                    # 自动批准大部分操作
confirm_destructive: true             # 删除文件等危险操作仍需确认
confirm_git_operations: false         # git 操作自动执行（提交、推送除外）

# 文件处理设置
max_file_size: 500KB                  # 最大文件处理大小
max_files_per_operation: 50           # 单次操作最大文件数

# 排除模式 - 这些文件/目录不会被自动处理
excluded_patterns:
  # 日志文件
  - "*.log"
  - "logs/*"
  
  # 依赖和缓存
  - "node_modules/*"
  - "__pycache__/*"
  - "*.pyc"
  - ".pytest_cache/*"
  
  # 版本控制
  - ".git/*"
  - ".gitignore"
  
  # 环境和配置
  - ".env"
  - ".env.local"
  
  # 构建产物
  - "dist/*"
  - "build/*"
  - "*.egg-info/*"
  
  # IDE 配置
  - ".vscode/*"
  - ".idea/*"
  - "*.swp"
  - "*.swo"

# 安全设置
security:
  allow_network_operations: true      # 允许网络操作（API调用等）
  allow_file_modifications: true      # 允许文件修改
  require_confirmation_for:
    - file_deletion                   # 删除文件需要确认
    - git_push                       # git推送需要确认
    - env_file_changes               # 环境文件修改需要确认

# 项目特定设置
project_settings:
  backend_directory: "backend"
  frontend_directory: "frontend" 
  docs_directory: "docs"
  
  # 常用命令简化
  common_commands:
    start_backend: "uvicorn backend.main:app --reload --port 8000"
    start_frontend: "cd frontend && npm run dev"
    docker_up: "docker-compose up -d"
    docker_logs: "docker-compose logs -f"

# 开发工具集成
tools:
  enable_linting: true                # 启用代码检查
  enable_formatting: true            # 启用代码格式化
  enable_type_checking: true         # 启用类型检查